export const sampleRate = 11000;
export const windowSize = 512;
export const nWindows = 64;
export const freqBinSize = windowSize / 2;
export const formantElemsPerWindow = 8;
export const elemsPerWindow = formantElemsPerWindow + freqBinSize;
export const interval = 32;
export const formantFloor = 200;
export const formantCeiling = 5500;
